export const types = {
  SIGNIN_REQUEST: '@auth/SIGNIN_REQUEST',
  SIGNIN_REQUEST_SUCCESS: '@auth/SIGNIN_REQUEST_SUCCESS',
  SIGNIN_REQUEST_FAILURE: '@auth/SIGNIN_REQUEST_FAILURE',
  LOGOUT: '@auth/LOGOUT',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
}
